vich_uploader:
    db_driver: orm

    mappings:
        location_image:
            uri_prefix: /images/locations
            upload_destination: '%kernel.project_dir%/public/images/locations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
